### ISSUE TITLE
vue3支持

### ISSUE THREAD

**Issue by Drswith** [Authing/authing-ui-components#2]
如题，本想在vue3中使用这个vue ui组件但是出现了一堆报错，是不是不支持vue3？版本vue3.2.x

**Comment by zhaoyiming0803** [comment]
> 

可以下载最新版本的 `@authing/vue-ui-components`，已兼容 Vue 3。

如果是基于 Vite 构建的应用，额外需要在 vite.config.js 中加如下配置：

``` js
export default defineConfig({
  optimizeDeps: {
    include: ['@authing/native-js-ui-components']
  }
})
```
